<img style="float: left;;" src='Imagenes/iteso.jpg' width="50" height="100"/></a>

# <center> <font color= #000047> Módulo 2: Fundamentos de Numpy




<img style="float: right; margin: 0px 0px 15px 15px;" src="https://upload.wikimedia.org/wikipedia/commons/1/1a/NumPy_logo.svg" width="400px" height="400px" />

> Hasta ahora sólo hemos hablado acerca de tipos (clases) de variables y funciones que vienen por defecto en Python.

> Sin embargo, una de las mejores cosas de Python (especialmente si eres o te preparas para ser un científico de datos) es la gran cantidad de librerías de alto nivel que se encuentran disponibles.

> Algunas de estas librerías se encuentran en la librería estándar, es decir, se pueden encontrar donde sea que esté Python. Otras librerías se pueden añadir fácilmente.

> La primer librería externa que cubriremos en este curso es NumPy (Numerical Python).


Referencias:
- https://www.numpy.org/
- https://towardsdatascience.com/first-step-in-data-science-with-python-numpy-5e99d6821953
___

# 0. Motivación 

¿Recuerdan algo de álgebra lineal? Por ejemplo:
- vectores;
- suma de vectores;
- producto por un escalar ...

¿Cómo se les ocurre que podríamos manejar lo anterior en Python?

In [65]:
# Crear dos vectores
x = [1,2,3,4]
y = [2,5,7,8]
x+y

[1, 2, 3, 4, 2, 5, 7, 8]

In [66]:
# Suma de vectores


In [67]:
# ¿con ciclos quizá?
[x[i] + y[i] for i in range(len(x))]

[3, 7, 10, 12]

In [68]:
# Producto por escalar
3*x

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [69]:
# ¿con ciclos quizá?
[3*x[i] for i in range(len(x))]

[3, 6, 9, 12]

### Solución: NumPy

NumPy es la librería fundamental para computación científica con Python. Contiene, entre otros:
- una clase de objetos tipo arreglo N-dimensional muy poderso;
- funciones matemáticas sofisticadas;
- herramientas matemáticas útiles de álgebra lineal, transformada de Fourier y números aleatorios.

Aparte de sus usos científicos, NumPy puede ser usada como un contenedor eficiente de datos multidimensional, lo que le otorga a NumPy una capacidad impresionante de integración con bases de datos.

Por otra parte, casi todas las librerías de Python relacionadas con ciencia de datos y machine learning tales como SciPy (Scientific Python), Mat-plotlib (librería de gráficos), Scikit-learn, dependen de NumPy razonablemente.

Para nuestra fortuna, NumPy ya viene instalado por defecto en la instalación de Anaconda.

Así que si queremos empezar a utilizarlo, lo único que debemos hacer es importarlo:

In [70]:
# Importar numpy
import numpy as np

In [71]:
np.pi

3.141592653589793

Lo que acabamos de hacer es un procedimiento genérico para importar librerías:
- se comienza con la palabra clave `import`;
- a continuación el nombre de la librería, en este caso `numpy`;
- opcionalmente se puede incluir una cláusula `as` y una abreviación del nombre de la librería. Para el caso de NumPy, la comunidad comúmente usa la abreviación `np`.

Ahora, intentemos hacer lo mismo que que antes, pero con el arreglo n-dimensional que provee NumPy como vector:

In [72]:
# Ayuda sobre arreglo N-dimensional
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if ``__array__`` returns a copy, if obj is a nested
        sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, etc.).
  

In [73]:
# Crear dos vectores
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [74]:
type(x)

numpy.ndarray

In [75]:
y = np.array([4,5,6,7,8])
y

array([4, 5, 6, 7, 8])

In [76]:
len(x), sum(x)

(5, 15)

In [77]:
# Suma de vectores
x + y

array([ 5,  7,  9, 11, 13])

In [78]:
# Producto interno
x.dot(y)

100

In [79]:
l1 = [1, 'x', False, min]
l1

[1, 'x', False, <function min>]

### Diferencias fundamentales entre Listas de Python y Arreglos de NumPy

Mientras que las listas y los arreglos tienen algunas similaridades (ambos son colecciones ordenadas de valores), existen ciertas diferencias abismales entre este tipo de estructuras de datos:

- A diferencia de las listas, todos los elementos en un arreglo de NumPy deben ser del mismo tipo de datos (esto es, todos enteros, o flotantes, o strings, etc).

- Por lo anterior, los arreglos de NumPy soportan operaciones aritméticas y otras funciones matemáticas que se ejecutan en cada elemento del arreglo. Las listas no soportan estos cálculos.

- Los arreglos de NumPy tienen dimensionalidad.

In [80]:
xx = np.array([[1,2,3],[2,3,4]])
xx

array([[1, 2, 3],
       [2, 3, 4]])

In [81]:
type(xx)

numpy.ndarray

In [82]:
xx.ndim

2

In [83]:
xx = np.array([[[1,2,3],[2,3,4]]])

In [84]:
xx.ndim

3

# 1. ¿Qué podemos hacer en NumPy?

Ya vimos como crear arreglos básicos en NumPy, con el comando `np.array()`

¿Cuál es el tipo de estos arreglos?

In [85]:
type(x)

numpy.ndarray

También podemos crear arreglos multidimensionales:

In [86]:
# Matriz 4x5
xx

array([[[1, 2, 3],
        [2, 3, 4]]])

In [87]:
# Tipo


In [88]:
# Atributos
xx.shape

(1, 2, 3)

In [89]:
xx = np.array([[1,2,3],[2,3,4]])
xx

array([[1, 2, 3],
       [2, 3, 4]])

In [90]:
xx.shape

(2, 3)

In [91]:
print(xx)

[[1 2 3]
 [2 3 4]]


## 1.1 Funciones de NumPy

Seguiremos nuestra introducción a NumPy mediante la resolución del siguiente problema:

### Problema 1

> Dados cinco (5) contenedores cilíndricos con diferentes radios y alturas que pueden variar entre 5 y 25 cm, encontrar:
> 1. El volumen del agua que puede almacenar cada contenedor;
> 2. El volumen total del agua que pueden almacenar todos los contenedores juntos;
> 3. Cual contenedor puede almacenar más volumen, y cuanto;
> 4. Cual contenedor puede almacenar menos volumen, y cuanto;
> 5. Obtener la media, la mediana y la desviación estándar de los volúmenes de agua que pueden ser almacenados en los contenedores.

Antes que nada, definamos las variables que nos dan:

In [92]:
# Definir numero de contenedores, medida minima y medida maxima
n_contenedores = 5
medida_min = 5
medida_max = 25

A continuación, generaremos un arreglo de números enteros aleatorios entre 5 y 25 cm que representarán los radios y las alturas de los cilindros:

In [93]:
# Ayuda de np.random.randint()
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)

    Return random integers from `low` (inclusive) to `high` (exclusive).

    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).

    .. note::
        New code should use the `~numpy.random.Generator.integers`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
     

In [94]:
# Números aleatorios que representan radios y alturas.
# Inicializar la semilla
medidas = np.random.randint(medida_min, medida_max+1, size=(10,))
medidas

array([ 7,  6, 22,  6, 15, 11, 19,  6,  7,  6])

In [95]:
# Ver valores
medidas

array([ 7,  6, 22,  6, 15, 11, 19,  6,  7,  6])

In [96]:
# array.reshape
medidas.shape

(10,)

In [97]:
medidas = medidas.reshape((2,5))
medidas


array([[ 7,  6, 22,  6, 15],
       [11, 19,  6,  7,  6]])

In [98]:
medidas.shape

(2, 5)

De los números generados, separemos los que corresponden a los radios, y los que corresponden a las alturas:

In [99]:
# Radios
radios = medidas[0, :]
radios

array([ 7,  6, 22,  6, 15])

In [100]:
# Alturas
alturas = medidas[1, :]
alturas

array([11, 19,  6,  7,  6])

$$ V = \pi*r^2*h$$

1. Con lo anterior, calculemos cada uno los volúmenes:

In [101]:
radios**2

array([ 49,  36, 484,  36, 225])

In [102]:
alturas


array([11, 19,  6,  7,  6])

In [103]:
np.pi

3.141592653589793

In [104]:
# Volúmenes de los contenedores
volumenes = (np.pi*radios**2)*alturas
volumenes

array([1693.31844028, 2148.84937506, 9123.18506602,  791.6813487 ,
       4241.15008235])

<img style="float: right; margin: 0px 0px 15px 15px;" src="https://upload.wikimedia.org/wikipedia/commons/b/b3/Symbol_great.svg" width="400px" height="400px" />

### ¡Excelente!

Con esta línea de código tan sencilla, pudimos obtener de un solo jalón todos los volúmenes de nuestros contenedores.

Esta es la potencia que nos ofrece NumPy. Podemos operar los arreglos de forma rápida, sencilla, y muy eficiente.

2. Ahora, el volumen total

In [105]:
# Volumen total
volumenes

array([1693.31844028, 2148.84937506, 9123.18506602,  791.6813487 ,
       4241.15008235])

In [106]:
volumenes.sum()

17998.184312415928

In [107]:
sum(volumenes)

17998.184312415928

3. ¿Cuál contenedor puede almacenar más volumen? ¿Cuánto?

In [108]:
volumenes


array([1693.31844028, 2148.84937506, 9123.18506602,  791.6813487 ,
       4241.15008235])

In [109]:
# Contenedor que puede almacenar más volumen
volumenes.argmax()

2

In [110]:
# Volumen máximo
volumenes[volumenes.argmax()]

9123.18506602476

In [111]:
volumenes.max()

9123.18506602476

In [112]:
# También se puede, pero no es recomendable. Ver comparación de tiempos
max(volumenes)

9123.18506602476

In [113]:
max([1,2,3,4])

4

In [114]:
max((1,2,3,4))

4

In [115]:
[1,2,3,4].max()

AttributeError: 'list' object has no attribute 'max'

4. ¿Cuál contenedor puede almacenar menos volumen? ¿Cuánto?

In [116]:
volumenes.argmin()

3

In [117]:
# Contenedor que puede almacenar menos volumen
volumenes[volumenes.argmin()]

791.6813487046279

In [118]:
# Volumen mínimo


5. Media, mediana y desviación estándar de los volúmenes

In [119]:
# Media, mediana y desviación estándar
volumenes.mean(), volumenes.std(),  np.median(volumenes)

(3599.6368624831857, 2984.78047420427, 2148.8493750554185)

In [120]:
np.median(volumenes)

2148.8493750554185

In [121]:
# Atributos shape y dtype


## 1.2 Trabajando con matrices

### Problema 2

> 25 cartas numeradas de la 1 a la 25 se distribuyen aleatoriamente y en partes iguales a 5 personas. Encuentre la suma de cartas para cada persona tal que: 
> - para la primera persona, la suma es el valor de la primera carta menos la suma del resto de las cartas;
> - para la segunda persona, la suma es el valor de la segunda carta menos la suma del resto de las cartas;
> - y así sucesivamente ...

> La persona para la cual la suma sea mayor, será el ganador. Encontrar el ganador.

Lo primero será generar los números del 1 al 25. ¿Cómo podemos hacer esto?

np.arange = np.array(range)

In [122]:
# Ayuda en la función np.arange()
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)

    Return evenly spaced values within a given interval.

    ``arange`` can be called with a varying number of positional arguments:

    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.

    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.

    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.

    See the Warning sections 

In [123]:
# Números del 1 al 25
cartas=np.arange(1,26)
cartas

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [124]:
np.array(range(1,26))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

Luego, tal y como en un juego de cartas, deberíamos barajarlos, antes de repartirlos:

In [126]:
# Ayuda en la función np.random.shuffle()
help(np.random.shuffle)

Help on built-in function shuffle:

shuffle(...) method of numpy.random.mtrand.RandomState instance
    shuffle(x)

    Modify a sequence in-place by shuffling its contents.

    This function only shuffles the array along the first axis of a
    multi-dimensional array. The order of sub-arrays is changed but
    their contents remains the same.

    .. note::
        New code should use the `~numpy.random.Generator.shuffle`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    x : ndarray or MutableSequence
        The array, list or mutable sequence to be shuffled.

    Returns
    -------
    None

    See Also
    --------
    random.Generator.shuffle: which should be used for new code.

    Examples
    --------
    >>> arr = np.arange(10)
    >>> np.random.shuffle(arr)
    >>> arr
    [1 7 5 2 9 4 3 6 0 8] # random

    Multi-dimensional arrays are only shuffled along the first axis:

 

In [127]:
# Barajar
np.random.shuffle(cartas)

In [128]:
# Ver valores
cartas

array([ 5,  2,  8,  3, 18,  1,  6, 16, 10,  9, 19, 22, 23, 20,  7, 21, 13,
       24, 15, 17,  4, 11, 14, 12, 25])

Bien. Ahora, deberíamos distribuir las cartas. Podemos imaginarnos la distribución como una matriz 5x5:

In [129]:
# Repartir cartas
cartas=cartas.reshape((5,5))
cartas

array([[ 5,  2,  8,  3, 18],
       [ 1,  6, 16, 10,  9],
       [19, 22, 23, 20,  7],
       [21, 13, 24, 15, 17],
       [ 4, 11, 14, 12, 25]])

In [130]:
# Ver valores
cartas[0,:]

array([ 5,  2,  8,  3, 18])

In [132]:
cp1=cartas[0,:]
sumap1 =cp1[0] - np.sum(cp1[1:])
sumap1

-26

In [134]:
cp2=cartas[1,:]
sumap2 =cp2[1] - cp2[0]-np.sum(cp2[2:])
sumap2

-30

Entonces, tenemos 5 cartas para cada una de las 5 personas, visualizadas como una matriz 5x5.

Lo único que nos falta es encontrar la suma para cada uno, es decir, sumar el elemento de la diagonal principal y restar las demás entradas de la fila (o columna).

¿Cómo hacemos esto?

In [135]:
# Ayuda en la función np.eye()
I5 = np.eye(5)
I5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [136]:
# Matriz con la diagonal principal
cartas*I5

array([[ 5.,  0.,  0.,  0.,  0.],
       [ 0.,  6.,  0.,  0.,  0.],
       [ 0.,  0., 23.,  0.,  0.],
       [ 0.,  0.,  0., 15.,  0.],
       [ 0.,  0.,  0.,  0., 25.]])

In [139]:
# Ayuda en la función np.ones()
complemento = np.ones((5,5)) - I5
complemento

array([[0., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1.],
       [1., 1., 0., 1., 1.],
       [1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 0.]])

In [140]:
# Matriz con los elementos fuera de la diagonal negativos
complemento*cartas

array([[ 0.,  2.,  8.,  3., 18.],
       [ 1.,  0., 16., 10.,  9.],
       [19., 22.,  0., 20.,  7.],
       [21., 13., 24.,  0., 17.],
       [ 4., 11., 14., 12.,  0.]])

In [143]:
complemento*cartas

array([[ 0.,  2.,  8.,  3., 18.],
       [ 1.,  0., 16., 10.,  9.],
       [19., 22.,  0., 20.,  7.],
       [21., 13., 24.,  0., 17.],
       [ 4., 11., 14., 12.,  0.]])

In [145]:
cartas*I5 - complemento*cartas

array([[  5.,  -2.,  -8.,  -3., -18.],
       [ -1.,   6., -16., -10.,  -9.],
       [-19., -22.,  23., -20.,  -7.],
       [-21., -13., -24.,  15., -17.],
       [ -4., -11., -14., -12.,  25.]])

In [149]:
m1 = complemento*cartas
m1

array([[ 0.,  2.,  8.,  3., 18.],
       [ 1.,  0., 16., 10.,  9.],
       [19., 22.,  0., 20.,  7.],
       [21., 13., 24.,  0., 17.],
       [ 4., 11., 14., 12.,  0.]])

In [150]:
m1.sum(axis=1)

array([31., 36., 68., 75., 41.])

In [151]:
(complemento*cartas).sum(axis=1)

array([31., 36., 68., 75., 41.])

In [146]:
(cartas*I5 - complemento*cartas).sum(axis=1)

array([-26., -30., -45., -60., -16.])

In [152]:
# Matriz completa
Mcompleta=(cartas*I5 - complemento*cartas)
Mcompleta

array([[  5.,  -2.,  -8.,  -3., -18.],
       [ -1.,   6., -16., -10.,  -9.],
       [-19., -22.,  23., -20.,  -7.],
       [-21., -13., -24.,  15., -17.],
       [ -4., -11., -14., -12.,  25.]])

In [154]:
sumas=Mcompleta.sum(axis=1)
sumas

array([-26., -30., -45., -60., -16.])

In [155]:
# Sumar por filas
sumas.max()

-16.0

In [156]:
print(f'La persona ganadora es Persona {sumas.argmax()+1}')

La persona ganadora es Persona 5


¿Quién es el ganador?

# 2. Algo de álgebra lineal con NumPy

Bueno, ya hemos utilizado NumPy para resolver algunos problemas de juguete. A través de estos problemas, hemos introducido el tipo de objetos que podemos manipular con NumPy, además de varias funcionalidades que podemos utilizar.

Pues bien, este tipo de objetos nos sirven perfectamente para representar vectores y matrices con entradas reales o complejas... si, de las que estudiamos en algún momento en álgebra lineal.

Mejor aún, NumPy nos ofrece un módulo de álgebra lineal para efectuar las operaciones básicas que podríamos necesitar.

Consideremos la siguiente matriz:

In [157]:
A = np.array([[1,0,1],
              [-1,2,4],
              [2,1,1]])
A

array([[ 1,  0,  1],
       [-1,  2,  4],
       [ 2,  1,  1]])

Podemos obtener varios cálculos útiles alrededor de la matriz A:

In [158]:
# Rango de la matriz A
np.linalg.matrix_rank(A)

3

In [159]:
# Determinante de la matriz A
np.linalg.det(A)

-7.000000000000001

In [160]:
# Inversa de la matriz A
np.linalg.inv(A)

array([[ 0.28571429, -0.14285714,  0.28571429],
       [-1.28571429,  0.14285714,  0.71428571],
       [ 0.71428571,  0.14285714, -0.28571429]])

In [ ]:
# BA != AB
# inv(A)A = Ainv(A)

In [161]:
# Potencia de la matriz A
# A.dot(A).dot(A).dot(A).dot(A)
A**2

array([[ 1,  0,  1],
       [ 1,  4, 16],
       [ 4,  1,  1]])

In [162]:
#A^2 = AxA
A.dot(A)

array([[ 3,  1,  2],
       [ 5,  8, 11],
       [ 3,  3,  7]])

In [163]:
# Eigenvalores y eigenvectores de la matriz A det(\lambdaI - A) = 0  ---> raices del polinomio
l,v = np.linalg.eig(A)


In [164]:
l

array([-1.25341804,  1.48003063,  3.77338741])

In [166]:
v

array([[ 0.25358082,  0.47881379,  0.15600857],
       [ 0.78049461, -0.84729481,  0.8879505 ],
       [-0.5714236 ,  0.22984529,  0.4326722 ]])

Por otra parte, si tenemos dos vectores:

In [168]:
x_array =np.array([1,2,3,4])
y_array=np.array([5,6,7,8])

podemos calcular su producto interno (producto punto)

In [169]:
x_array.dot(y_array)

70

De la misma manera, podemos calcular la multiplicación de la matriz A por un vector

In [170]:
A

array([[ 1,  0,  1],
       [-1,  2,  4],
       [ 2,  1,  1]])

In [171]:
z=np.array([1,0,1])
z

array([1, 0, 1])

In [174]:
help(np.dot)

Help on _ArrayFunctionDispatcher in module numpy:

dot(...)
    dot(a, b, out=None)

    Dot product of two arrays. Specifically,

    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).

    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.

    - If either `a` or `b` is 0-D (scalar), it is equivalent to
      :func:`multiply` and using ``numpy.multiply(a, b)`` or ``a * b`` is
      preferred.

    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.

    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of
      `b`::

        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

    It uses an optimized BLAS library when possible (see `numpy.linalg`).

    Parameters
    ----------
    a : array_like
        Fir

In [172]:
A.dot(z)

array([2, 3, 3])

In [173]:
A@z

array([2, 3, 3])

In [175]:
z@A


array([3, 1, 2])

In [177]:
z.reshape((3,1))

array([[1],
       [0],
       [1]])

In [178]:
z.reshape((1,3))

array([[1, 0, 1]])

In [179]:
z@A

array([3, 1, 2])

In [183]:
z = z.reshape((3,1))
z

array([[1],
       [0],
       [1]])

In [184]:
z

array([[1],
       [0],
       [1]])

In [185]:
z@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

$$
A x = z
$$

In [187]:
A, z

(array([[ 1,  0,  1],
        [-1,  2,  4],
        [ 2,  1,  1]]),
 array([[1],
        [0],
        [1]]))

In [186]:
np.linalg.inv(A)@z

array([[ 0.57142857],
       [-0.57142857],
       [ 0.42857143]])

**Recomendado el siguiente [tutorial](https://www.numpy.org/devdocs/user/quickstart.html) para que profundicen más en todo lo que pueden hacer con NumPy**